#setup server
server:
  port: 9999
  servlet:
    context-path: /

spring:
  application:
    name: audit-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://38.242.206.98:5430/audit
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

openapi:
  service:
    title: audit-service doc
    version: 1.0.0
    url: http://38.242.206.98:8081
springdoc:
  api-docs:
    path: /audit-service/v3/api-docs
  swagger-ui:
    path: /audit-service/swagger-ui.html

logging:
  level:
    web: debug
    audit-service: debug